### ISSUE TITLE
GitLab CI pipeline integration docs not working

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-hugo#1076]
From a user on the Pulumi Community Slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1580740048408200

----

I’ve followed the [docs](https://www.pulumi.com/docs/guides/continuous-delivery/gitlab-ci/) for a GitLab pipeline and pulumi is not found.  Yes, I’m updating my path:

```
=== Pulumi is now installed! 🍹 ===
+ Please add /root/.pulumi/bin to your $PATH
+ Get started with Pulumi: https://www.pulumi.com/docs/quickstart
$ export PATH=$PATH:$HOME/.pulumi/bin
$ which pulumi
/root/.pulumi/bin/pulumi
$ cd pulumi
$ pulumi login
/bin/sh: eval: line 96: pulumi: not found
```

**Comment by toriancrane** [comment]
Due to limited details in the original issue as well as the slack thread being over 90 days old, I was unable to acquire the context that I needed to reproduce the initial problem. If anyone can provide history/context here, that would be helpful.

In the meantime, I have made some updates to the content to provide more clarity on the topics covered and to update the NodeJS installation scripting which had soon to be deprecated code.
