### ISSUE TITLE
Indicate there is more content in left nav

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/pulumi-hugo#1178]
if a user configures the open menus so that part of the left nav is no longer visible then a scroll bar should be visible, even on osx (we should also consider other affordances to communicate more content)

Pulled out from https://github.com/pulumi/pulumi-hugo/issues/561 as it's own issue, due to some specific user feedback on this point: https://pulumi-community.slack.com/archives/CLBMM3BS9/p1646783852965519

**Comment by jonelleb** [comment]
# [Figma File](https://www.figma.com/file/8kz7uSX7MD430hCwl7q8Ll/Jonelle's-Miscellaneous-Work?node-id=23%3A767)

**New/Updated Left Nav Design:**

<img width="833" alt="Screen Shot 2022-03-22 at 11 44 50 AM" src="https://user-images.githubusercontent.com/100616532/159534614-5e364be7-3220-47bb-a629-10885999f0ba.png">

# Design Changes

- Within the new anchor links, the link that the user is on is in bold indicating to the user that this is the content being displayed in the page right now.

- If the user clicks on any of the other anchor links, 'User Guides' for example, the left nav underneath should focus on the 'User Guides' section and the page content should change to reflect that as well. ('User Guides' would then be bold instead of 'Getting Started'.)

<img width="273" alt="Screen Shot 2022-03-22 at 12 04 24 PM" src="https://user-images.githubusercontent.com/100616532/159535674-be908f18-d48c-4b61-8fda-773b53445f58.png">

# Additional Changes

**Optional Add-on to the updated left nav:**
*(If possible and time allows? Great! If not? No worries.)*

<img width="173" alt="Screen Shot 2022-03-22 at 11 58 29 AM" src="https://user-images.githubusercontent.com/100616532/159536057-a3d9baa8-bcb1-457d-9244-2a9156b85851.png">

- If user clicks 'Expand all', all of the left nav headers (i.e - Intro, User Guides, Converters, Reference) will expand - but this does NOT expand all of the the links underneath of those headers.
- 'Collapse all' collapses all of the left nav headers.
- Gray expand (down carrot) icons are placed next to all of the left nav headers so that the user can expand or collapse them whenever they want.

<img width="828" alt="Screen Shot 2022-03-22 at 12 08 21 PM" src="https://user-images.githubusercontent.com/100616532/159536422-97fe5720-3e3d-4b0a-b43c-1cf2456dc186.png">

# Engineer Notes
- Susan mentioned that if there was any way possible to have the scrollbar within the left nav showing all the time, in all browsers, that's what they would prefer and I agree that this would definitely help.
- Comments have been added in Figma but please feel free to reach out with any questions or concerns

Thanks!

**Comment by jonelleb** [comment]
@susanev - I updated the design in Figma (updating the image posted on this issue) and responded back to Christian's concern in Slack.

**Comment by jonelleb** [comment]
# Design Updates & Engineer Notes

*Tagging @kimberleyamackenzie*
 
**After previewing the work done so far, new design work was needed:**
- There were some concerns about not having starter pages for Converters and Support. Since all of the other sections of the left nav have starter pages, to keep consistency and to properly link the anchor links  that are now above the left nav, new pages need to be designed.
-  After a user clicks one of the anchor links, we want a way to visually show the user that they are in that section of the nav. 

## Updated Left Nav Behavior 

When a user clicks on one of the anchor links, the left nav will focus on that section and a blue vertical bar will appear to the right of that link as well as the link itself will glow/be highlighted for a few seconds (I'd say no more than 5 seconds, but please feel free to use your best judgment) to indicate to the user that the nav has moved to that section. The vertical blue bar will stay as long as the user is still in any link within that section.

**Please see new [Figma Prototype](https://www.figma.com/proto/8kz7uSX7MD430hCwl7q8Ll/Jonelle's-Work?page-id=23%3A767&node-id=107%3A1345&viewport=358%2C48%2C1.96&scaling=min-zoom&starting-point-node-id=107%3A1345) and click Getting Started, Converters or Support in the anchor links above the left nav to see examples of how I'm thinking the glow/highlight of the link should look & behave.**

![Screen Shot 2022-04-19 at 12 46 19 PM](https://user-images.githubusercontent.com/100616532/164065160-eca98f1f-bf09-41b5-b422-db2c94a419ac.png)

![Screen Shot 2022-04-19 at 12 46 25 PM](https://user-images.githubusercontent.com/100616532/164065183-053c954f-3795-4bf2-8af9-ce1a8d555279.png)

![Screen Shot 2022-04-19 at 12 46 33 PM](https://user-images.githubusercontent.com/100616532/164065246-53587cee-acb0-4e5a-97ac-5e8129b4f599.png)

## New Converters and Support Pages

**Converters**

![Screen Shot 2022-04-19 at 12 45 30 PM](https://user-images.githubusercontent.com/100616532/164066159-679b3380-6667-49f6-9f2b-a935a911225f.png)

**Support**

Both the Troubleshooting and FAQ headers should link to their pages (just as in similar page templates are set up in Docs).
I'm honestly not sure what the right summary text should be that's below the 'Support' header. Maybe @susanev can give some guidance? Or we can all decide together the next time we meet. For now I've just used 'lorem ipsum' dummy text.

![Screen Shot 2022-04-19 at 12 45 47 PM](https://user-images.githubusercontent.com/100616532/164066463-8538f8ef-e858-44ed-8c31-7af0243b7afd.png)

# [Figma File](https://www.figma.com/file/8kz7uSX7MD430hCwl7q8Ll/Jonelle's-Work?node-id=107%3A1469)
*same link as before, new designs are under a label that says 'FINAL DESIGN - UPDATE (April 19, 2022)'*

# [Figma Prototype](https://www.figma.com/proto/8kz7uSX7MD430hCwl7q8Ll/Jonelle's-Work?page-id=23%3A767&node-id=107%3A1345&viewport=358%2C48%2C1.96&scaling=min-zoom&starting-point-node-id=107%3A1345)
*If you're having any issues with seeing the animations again, just click the 'restart' button that appears when you hover on the lower left side of the screen.*

**Comment by jonelleb** [comment]
@kimberleyamackenzie 

Updated text for Converters and Support pages have been added in Figma. Thanks!

![Screen Shot 2022-04-20 at 12 19 55 PM](https://user-images.githubusercontent.com/100616532/164287531-afa10e05-330a-4bbf-b828-f57e10f5ca3e.png)

![Screen Shot 2022-04-20 at 12 20 13 PM](https://user-images.githubusercontent.com/100616532/164287556-f76930b2-647a-4d9e-b0b1-d056c7115d52.png)

**Comment by susanev** [comment]
fixed by https://github.com/pulumi/theme/pull/108
