### ISSUE TITLE
Redesign language selectors for space-saving

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/pulumi-hugo#1199]
## Overview
Currently, our registry and docs use tabs for language selection. However, if we were to support additional languages down the line, we would quickly run out of horizontal space. We need to redesign selectors with space-saving in mind, so in the future we can accommodate changes to our offering.
![image](https://user-images.githubusercontent.com/97129308/157763866-4841aae0-aa68-494a-80f1-0c053facbf24.png)

## Considerations

- Often the first modification that can be made when running out of horizontal tabs is to transition into vertical tabs. However, both our Docs and Registry already have competing vertically displayed information. Introducing more vertical information would further shrink the maximum width of core content, and is not a recommended option in this case.
- Now, with only a handful of languages, it's ideal to see all four tab headings so users immediately know what options are available to them. However, if those options grow, we should expect to lose the ability to expose all languages at once as a function of space-saving

## Design Changes
- Tabs have been exchanged for a dropdown selector which can accommodate additional language options. Mock-up models extra languages for demonstration purposes.
- Languages are listed alphabetically with TypeScript still selected by default.
![Dropdown Expanded (5)](https://user-images.githubusercontent.com/97129308/157763815-eae03dd5-5730-4aaa-9424-41d717c8cfff.png)
![Dropdown (2)](https://user-images.githubusercontent.com/97129308/156708599-90083488-a286-47ef-bc08-7225c8b9e338.png)
- Existing functionality is not impacted. If a language is chosen on one page, that decision is remembered across all pages until the selection is toggled again.

## Handoff Notes
- If it's easily accessible, the dropdown component is the same one we use in the Registry, the only change being the options are radios instead of checkboxes.

**Comment by joeduffy** [comment]
I think this is probably the best approach, and it looks very good. The only thing that gave me pause was that I can no longer see at a glance what all of the options are. With the old design if I’m a Python person, I can see and right away connect with the fact that there’s a Python option. Now I need to click something to see it. Did you worry about this too? I don’t really have a counter proposal but figured I would mention since it’s the first impression and thought that came to mind.

**Comment by jkodroff** [comment]
The fundamental design is solid IMO and an obvious improvement. Nice work!

Some feedback:

* Because of the rainbow beneath Selected Language, the label/drop-down combo isn't visually obvious to me that it's a form field - it looks more like a textual heading rather than a control. Not sure what the fix is. Maybe a grey background or 1px border around both the label and form field?
* Would adding icons for each language clutter things up, or Make It Pop?

Some notes on the technical side:

I'm excited that losing the tabs would significantly improve our docs in a major way with nearly no additional effort: The way we parse docs today expects any sample code to be in an "Example Usage" section, to which we add the template macro that creates the tabs. We massage the upstream TF docs to get our expected structure, but we often are not able to recognize examples because TF providers put examples in non-standard places in a doc, which makes the sample code display without tabs and does not look good ([example](https://www.pulumi.com/registry/packages/gcp/api-docs/organizations/getorganization/)).

With this change I believe we would just show/hide based on a simple CSS selector (the code blocks render as e.g. `<code class="language-typescript" data-lang="typescript">` and would no longer need to inject a macro to get show/hide for all code examples on the page. Even when the tabs do not correctly render, the `<code>` tag does render, so that means we'll be able to correctly display examples even when they are not present in the expected place in the upstream docs.

When it comes time for implementation, I believe that the Bridge will need to change, because the Description and Examples are stored in a single text blob with the template macro (`{{% examples %}}`) embedded in the generated schema, so please coordinate with the Providers team. I believe we would also need to update the bridge and re-deploy all providers, because the tabs macro is embedded in the schema.

**Comment by susanev** [comment]
@joeduffy im a bit worried about the same thing but not a lot worried. though i think there are two approaches we could take to address this...
- add help text below the drop down that states something like "We support x languages"; this will need to adjust though in situations where that example only supports x-y languages.
- add something to the footer reinforcing all the languages we support (though this should not increase the scope of this current issue, but we can come back with a followup issue)

@anita-trimbur what do you think? do you have other ideas?

**Comment by susanev** [comment]
@kimberleyamackenzie do you have thoughts on @jkodroff tech feedback? i was hoping we could do this with CSS but if not then we should make sure to coordinate and plan with the provider's team.

**Comment by susanev** [comment]
and @jkodroff this is the current design of our dropdowns, beyond just this experience. we can take your feedback and figure out how to adjust them everywhere but would rather not increase the scope of this work to address that.

@anita-trimbur i think it would be worth exploring how we could bring the language logos into the experience, as Josh calls out.

**Comment by jkodroff** [comment]
@susanev @kimberleyamackenzie If we can simply ignore the `{{% examples %}}` macro (make it a no-op), we wouldn't have to change the bridge. If we cannot ignore the macro, we would need to update the bridge on all providers and re-release them all. Not the end of the world, but not trivial either.

**Comment by lukehoban** [comment]
I've looked at this a few times, and each time I feel like I expect we can do something better - but I'm not sure I know what concretely to suggest yet.  A few thoughts/questions:
1. The "Selected Language" with the rainbow underline is *very* prominent, but doesn't actually really seem necessary.  We don't have anything like that today, it isn't really part of the useful content of the page, and I expect it will  feel quite noisy on pages like https://www.pulumi.com/docs/intro/concepts/inputs-outputs/ (and lots of others) that have a lot of code snippets.
2. The styling of the dropdown feels like it could be "better" somehow
3. Are there other options we considered?  I feel like it would be interesting to look at 2-3 strong candidates for design approach.
4. Are there options to use icons instead of words to save space, and/or to pull this inside the code snippet bounding box?
5. Have we compared with other Framework documentation?  This isn't a completely unique problem for us, there's a fair bit of precedent for documenting multi-language APIs/frameworks - are there examples we feel of this being done really well?

**Comment by susanev** [comment]
@anita-trimbur i think we have enough feedback on this to continue and i also received some feedback from Christian by way of dm. lets plan to sync up about this next week.

**Comment by kimberleyamackenzie** [comment]
Following up from a conversation earlier in the week, here are some examples of places where we use the tabs for non-code, or for code but in a different way than the typical docs usage:

Homepage:
<img width="656" alt="Screen Shot 2022-03-17 at 10 02 10 AM" src="https://user-images.githubusercontent.com/25756367/158854569-bb93eb4f-e11c-4b35-84d7-979169137772.png">

/product/packages (code but not in the docs way)
<img width="1347" alt="Screen Shot 2022-03-17 at 10 03 46 AM" src="https://user-images.githubusercontent.com/25756367/158854808-32988a4e-023f-4f38-8ce4-5401b833e43f.png">

/solutions
<img width="1367" alt="Screen Shot 2022-03-17 at 10 04 59 AM" src="https://user-images.githubusercontent.com/25756367/158855029-0b90d716-ef9b-47ad-a558-9ee88d10a151.png">

We have a number of examples where we display a chooser, and that chooser updates code styled strings within a larger block of text:
<img width="653" alt="Screen Shot 2022-03-17 at 10 31 35 AM" src="https://user-images.githubusercontent.com/25756367/158860634-fff6d364-23cb-4945-8734-9144ad8b43de.png">

**Comment by kimberleyamackenzie** [comment]
@jkodroff I poked around, and I just want to confirm my understanding of your comment about the technical implementation.  It's my understanding after a short spike that we can implement the suggested design options purely in CSS/HTML/JS, on the component in theme alone, without touching docs at all.  Doing so would maintain existing behavior, including a few places where the selector doesn't render as expected.  If we want to improve on existing behavior, the new designs enable us to do so with some work from your team.  Is that right?
