### ISSUE TITLE
Incorrect button values

### ISSUE THREAD

**Issue by joebentaylor1995** [pulumi/pulumi-hugo#127]
Buttons don't have any transition easing and the padding sizes are incorrect.

## Expected behavior
Hover should have at least a `transition: all .25s ease-in-out;`
[Example provided with correct padding and transition](https://codepen.io/levinriegner/pen/b442b81d8b6fcefe7e38b61d35eeddac?editors=1100)

## Current behavior
Padding doesnt have enough top/bottom.
<img width="187" alt="Screenshot 2021-04-22 at 14 42 50" src="https://user-images.githubusercontent.com/54585427/115724644-0c707900-a379-11eb-8141-542ecbb9b0b1.png">

Hover is an [instant transition](https://www.loom.com/share/d89fa73fa8424e08b3bf76754a82d84d)

## Steps to reproduce
1. Go to [the website](https://www.pulumi.com/)
2. Hover over any purple button

## Affected feature
Primary Buttons

**Comment by susanev** [comment]
as mentioned we are somewhat limited in our padding values right now, but we should be able to add the transitions.

**Comment by joebentaylor1995** [comment]
@susanev 
Im not sure I understand, Tailwind can still support custom CSS, is there something im missing with this?

**Comment by susanev** [comment]
we are currently using tailwind version 1 and trying to align to that as much as possible. we know we can use custom css but have been trying not to, @cnunciato can speak to it more if you want more details. we hope to upgrade soon.

**Comment by joebentaylor1995** [comment]
@susanev 
I totally get the want to use as much tailwind as possible, but there will always be a need for custom code in parts of the site, my only question is if it's just a concern around timing and utilising what tailwind has to offer for that reason, ive provided the exact code needed to accomplish the fix of the bug, so why could this code not be used?

**Comment by susanev** [comment]
@cnunciato will speak to this when he is online.

**Comment by cnunciato** [comment]
Two things, here, padding and transition.

For the padding thing, understand with the redesign we weren't starting from scratch -- we had an already-very-large website with a lot of existing code, and a very short timeline within which to work. To go fast, we had to be able to draw on as much existing work as we could, and most of the site had already been coded on top of Tailwind defaults with regard to margins, padding, and so on. So it made sense to stick with those defaults for now, knowing they weren't perfect, because it let us to get _close_ to the designs without having to sacrifice all of the benefits (too many to name) that we get from using Tailwind. 

Of course, those defaults are just defaults. We can definitely customize them -- e.g., change the meaning of `px-12` in terms of actual `rem`s. But we wouldn't want to just change the value of `px-12` -- not without changing all of the other padding settings as well, because the scales within a given property, and the relationships between properties -- how all the margin settings relate to one another, how margins relate to padding, how padding relates to widths and heights, etc. --  are collectively what make the library so valuable. If we didn't do that, and just pasted code right out of Figma, over time we'd have a lot more custom CSS code, and a lot less internal consistency. So for all of these reasons, we try to stick to the Tailwind classes as much as possible, and look to custom CSS when we're doing something truly custom. 

So the thing to do here is just to adjust our Tailwind settings across the board such that all of our buttons inherit the right paddings and those paddings are consistent with margins and everything else, that all buttons have the same transitions, and so on. In other words, we'll get there -- it'll just take a but of time.

All of that said, I completely agree. I just wanted to make sure I explained why things are the way they are right now. 😄
