### ISSUE TITLE
Text readability on product page could use improvement

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/pulumi-hugo#1283]
Reported via tweet: https://twitter.com/AdamTReineke/status/1509591410789388291.  Report was specifically about the product page, but we should review other marketing pages as well.

"If you haven't looked at your Products page on a lower DPI monitor, I recommend checking it out. The text in the SVG looks not great."

![image](https://user-images.githubusercontent.com/25756367/161121540-5f77633e-bdcd-4dbb-a7db-70a79af8deef.png)

**Comment by susanev** [comment]
theres not much we can do here from the svg side of this, all the fonts are outlined and are vectors themselves.

we could detect when someone is using something that does not render svgs well and display the png instead, or we could build out this diagram in html and css instead of svg.

i did some very small clean-up to the svg which we could also try and see if it improves the experience for this person.

![product-platform-desktop](https://user-images.githubusercontent.com/5489125/161298728-2989fd9b-7358-4766-83c1-cd576b2c3a9c.svg)

![product-platform-desktop](https://user-images.githubusercontent.com/5489125/161298738-08ee3be4-801d-4628-be06-ad4fbdecf44a.png)

**Comment by susanev** [comment]
closing as wont fix, this is a safari issue
