### ISSUE TITLE
something happened to hover states on secondary buttons

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1308]
all secondary buttons throughout the website have white text on hover which is very difficult to see
secondary buttons should maintain their purple text on hover

**Comment by cnunciato** [comment]
This was filed today, which has a bit more info: https://github.com/pulumi/marketing/issues/210

I'll close it as a dupe, but wanted to link to it from here for anyone looking for more info.

**Comment by susanev** [comment]
ive gotta say, i really want tests for this. we have had this regression at least 3 times (though previously at a smaller scale).

**Comment by cnunciato** [comment]
I agree! 😄 

We already have the ability to support tests like these, by the way. We run Cypress on every deployment -- I use it to make a few calculations to ensure the CSS bundle was properly loaded and applied:

https://github.com/pulumi/docs/blob/e92237f6415aa7a26bd3fce458747ed10d394b91/cypress/integration/site_spec.js#L9-L15

Probably just a matter of adding another test once the fix is applied.
