### ISSUE TITLE
ip output not displaying in preview

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1553]
## overview
when following the get started guide for python+kubernetes, the deploy the changes step does not show that a new output was added in the preview, as the get started guide indicates.

https://www.pulumi.com/docs/get-started/kubernetes/deploy-changes/

## repro steps
- follow the python+kubernetes get started guide
- notice on the deploy the changes step, after removing the nave output and added ip it does not show that a new ip output is being added in the preview

## refs
- [internal slack thread](https://pulumi.slack.com/archives/C9SGX9QA1/p1653336580323109) including video clip of the user who hit this issue

**Comment by susanev** [comment]
@nimbinatus are you able to take fixing this?

**Comment by nimbinatus** [comment]
I'll be able to get to this in late June.

**Comment by toriancrane** [comment]
I am actually running into a different issue with this guide. `pulumi up` is not even registering `ingress` as a valid key.

```
  pulumi:pulumi:Stack (k8s-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/workspaces/.devcontainer/k8s/./__main__.py", line 44, in <lambda>
        ingress = frontend.status.apply(lambda v: v["load_balancer"]["ingress"][0] if "load_balancer" in v else None)
    KeyError: 'ingress'
```

The only way I was able to get it to work was to comment out everything from the "When done" comment down, run pulumi up, then uncomment and run it again. Still thinking through the best way to solve this.

I am also wondering about the use of this conditional in general. The original proposed solution was to update the Python code to add the IP address unconditionally, but does it make sense to do this even if there is no value returned to `ingress` ? Maybe for the purposes of a getting started guide it might be okay because the assumption is that the code will work as expected.
