### ISSUE TITLE
social imgs are cut off in bad ways

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#183]
the social img for linkedin is cut off, we should prolly just use the regular wordmark logo for that space

<img width="535" alt="linkedin" src="https://user-images.githubusercontent.com/5489125/116920922-18c1c500-ac08-11eb-8fe3-2ca23eb73849.png">

**Comment by cnunciato** [comment]
We should do this if we can, but it's not clear to me we can specify a different `og` (or other) image for LinkedIn previews. https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en

**Comment by cnunciato** [comment]
We'll probably want to update the image we use for Greenhouse listings also:

![image](https://user-images.githubusercontent.com/274700/122318386-ceed1f80-ced3-11eb-9a35-ffaa98649c53.png)

**Comment by susanev** [comment]
as an additional note, this is how our greenhouse links appear on twitter

<img width="533" alt="greenhouse-twitter" src="https://user-images.githubusercontent.com/5489125/122627679-f542c480-d065-11eb-89bb-84c2a8d38cfe.png">

**Comment by kimberleyamackenzie** [comment]
Pushing this to the next milestone, as we're pulling in https://github.com/pulumi/pulumi-service/issues/6596 as higher priority.  

A few findings for when this gets picked back up:
- We can't set multiple og:image tags for different sites, but in theory we should be able to get one image with the right ratios to work everywhere and/or set something specific up for twitter if that's the one outlier because they have their own tags.
- Testing this locally and with the site previews doesn't work :(.  Probably have to set up ngrok to test this, but haven't verified that works.
- For linkedin, image must be a 1.91:1 ratio (1200x627 px) and min 200px width
- To test + verify metadata without actually posting https://www.linkedin.com/post-inspector/

**Comment by SaraDPH** [comment]
Please add **<meta property="og:image:alt" content="Pulumi logo" />** and **<meta name="author" content="Pulumi">**

For the image can we do a small test to see if LinkedIn picks up the correct array? 

The goal is to keep the same image but add the dimensions, so it knows it is square, 
_<meta property="og:image" content="https://www.pulumi.com/logos/brand/twitter-card.png">_
**<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" />**

And add a second image for LinkedIn with its dimensions:

_<meta property="og:image" content="[image below]" />_
**<meta property="og:image:width" content="600" />
<meta property="og:image:height" content="313" />**

![pulumi-logo-linkedin](https://user-images.githubusercontent.com/100384099/157516193-8b830cae-f114-4487-bde5-f02cd68f560c.jpg)

**Comment by cnunciato** [comment]
Moving to use a rectangular `og:image` to fix this.

**Comment by cnunciato** [comment]
Just to update, we were able to specify an additional tag, `twitter:image`, to allow the square image to be used on Twitter by default and the rectangular one on LinkedIn.
