### ISSUE TITLE
missing clear info about properties and its values in learn fundamentals pathway

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-hugo#1840]
### What happened?

https://www.pulumi.com/learn/pulumi-fundamentals/configure-and-provision/

does talk about the variables

```
var config = ctx.config();
var frontendPort = config.requireInteger("frontendPort");
var backendPort = config.requireInteger("backendPort");
var mongoPort = config.requireInteger("mongoPort");
```
while the example above needs more properties too

such as

```
mongoHost:
mongoPort: 
nodeEnvironment: 
protocol: 

```

The value of these above 4 not clear, so  pl. include them in the documentation

### Steps to reproduce

run the pulumi up then code will complain about these props are not avaiable

### Expected Behavior

Value of these should be documened

### Actual Behavior

pulumi build fails with error that these properties are not known

### Output of `pulumi about`

G:\DWork\osource\cloudc\devops\pulumi\java\docker>pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
docker  3.2.0
java    unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in java: executable='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' version='java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)' java='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' javac='17.0.2'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/nagkumar
User           nagkumar
Organizations  nagkumar

No dependencies found

Pulumi locates its logs in C:\Users\RAJANA~1\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nimbinatus** [comment]
Hi there! If you read a bit farther in the pathway, those configuration values are added while creating the backend container:

> ![Screen Shot 2022-08-22 at 9 06 25 AM](https://user-images.githubusercontent.com/1538692/185941266-5c606461-b571-4851-b7cb-bc2f0c58abb5.png)

Would some extra headings help?

**Comment by nagkumar** [comment]
Thank You, still not clear, .env file is not part of the version control https://github.com/pulumi/tutorial-pulumi-fundamentals/tree/main/backend

Also not clear where the java pulumi file should be in the above source code,  May be if the entire source code is in verstion control it would help.

Also, tried some way.. but now landing up in this.. 

![image](https://user-images.githubusercontent.com/332234/186070377-11d63857-756a-42b1-b7b1-43c601136bff.png)

My directory structure is

![image](https://user-images.githubusercontent.com/332234/186070622-cb64a025-fcdb-4c6c-bb97-5953b527b32e.png)

![image](https://user-images.githubusercontent.com/332234/186070610-1aa5fb71-8baf-454f-8094-2297fdb3897a.png)

![image](https://user-images.githubusercontent.com/332234/186070686-c1505d05-751c-4047-9048-f5cfff6b5730.png)

**Comment by nagkumar** [comment]
Also, not clear if we need to first do npm install in all the directories or docker would take care it..

**Comment by nimbinatus** [comment]
Ah, I think I understand where you are. For the pathway, you do not need to have any of the application code that you can find at [`pulumi/tutorial-pulumi-fundamentals`](https://github.com/pulumi/tutorial-pulumi-fundamentals/). We reference it so you can explore the source code for the Docker containers, but we don't pull it down or build it. The `RemoteImage` call pulls directly from Docker Hub rather than building an image locally from code. I probably could make that clearer, but here's the part that notes that:
>In our case here, the Docker [RemoteImage](https://www.pulumi.com/registry/packages/docker/api-docs/remoteimage/) resource takes the following inputs:
>
> * an unnamed string: a name for the resource we are creating
> * `name`: the name of the remote image to pull down

And a link to the API if you want to dig in: https://www.pulumi.com/registry/packages/docker/api-docs/remoteimage/

Your Java app directory should be as follows:
```
<root>/
    .gitignore
    .gradle
    Pulumi.dev.yaml
    Pulumi.yaml
    app/
        build/
            ...
        build.gradle
        src/
            main/
                java/
                    my-first-app/
                        App.java
    gradle/
        ...
    gradlew
    gradlew.bat
    settings.gradle
```
And the Pulumi code is in `App.java`.

There is no need to do any `npm install` or anything else as that's already built into the Docker image that you're pulling down with `RemoteImage`.

**Comment by nagkumar** [comment]
>We reference it so you can explore the source code for the Docker containers, but we don't pull it down or build it. The RemoteImage 

then the title of this page is https://www.pulumi.com/learn/pulumi-fundamentals/create-docker-images/ completely off, it is about pulling the images from the dockerhub rather than saying it as creating docker images..

The current title of the page says it is to create docker image given the dockerfile and its source code.

If the current java code is to bring in the remote docker image, it is assumed that the main author of the image has done npm install and run docker command and uploaded the images to the hub etc..

My request is consider to have two topics

1. One is how to build docker image and upload to docker hub from the source code
2. 2nd one is how to pull that docker image and deploy it locally

hope this further clarifies the challenges I see.

**Comment by nimbinatus** [comment]
It sounds like you're looking for a tutorial on building Docker images with Pulumi. The Learn pathway you're referencing is teaching how Pulumi works, which is a different goal. Originally, we were building images, but we discovered that issues with using Docker on various platforms caused the focus to move from learning how to use Pulumi to debugging Docker. The content has since shifted to using remote images we own on DockerHub, so I agree that we should change those headings.

We can certainly add a ticket to build a tutorial on building images with Pulumi. At the moment, we do not have that content for Java, however, because the Java language host is still in preview and has not yet released an `Image` resource for Java (reference https://www.pulumi.com/registry/packages/docker/api-docs/image/), which means we cannot build images with Java.

**Comment by scottslowe** [comment]
@nagkumar Thanks for the feedback on this Learn pathway! I'll be opening a PR shortly that addresses your comments:

* I added some explanatory text around the purpose/use of the configuration values, and that it is required to set them with `pulumi config set` or else `pulumi up` reports an error
* I changed the heading to reflect that you are pulling an image, not building an image locally, and I've also updated the text accordingly
* I've updated the paths to the Dockerfiles and code in the associated repository (they had an extraneous `app` in front of the path that didn't need to be there)

I haven't renamed the file, which would result in a change to the path and may result in broken links. However, the content has been updated as described above.

Once the PR merges, this issue will close automatically; however, feel free to re-open it if you don't feel your feedback has been addressed.

Thank you!
