### ISSUE TITLE
CrossGuard main marketing page code formatting looks bad

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-hugo#2576]
On [the main CrossGuard marketing page](https://www.pulumi.com/crossguard/), the code formatting looks really bad:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/410614/226378639-9f2c9d88-f206-4b69-ae86-1eed84aefadd.png">

We should also consider demonstrating policies in both TypeScript and Python.

**Comment by scottslowe** [comment]
@susanev Do you know where this content lives in the `pulumi-hugo` repo? Or does it live in a different repo?

**Comment by jkodroff** [comment]
BTW, I think the formatting is messed up because it's not actually valid code.

**Comment by susanev** [comment]
@scottslowe this page is here: https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/layouts/page/crossguard.html

also very happy to demo githubs new search if ya ever would like, its much better now and can find things like this pretty easily

**Comment by jkodroff** [comment]
Also, see below:

1. "Requiring a specific cost allocation tags." <-- grammar
2. "A live dashboard of organizational violations in Pulumi Enterprise." <-- Should be "Pulumi Cloud"

![image](https://github.com/pulumi/pulumi-hugo/assets/410614/434c378b-9b6c-4e7a-938f-afba473e82ac)

**Comment by cnunciato** [comment]
Noticed this page is affected also:

https://www.pulumi.com/crosswalk/kubernetes/

![image](https://github.com/pulumi/pulumi-hugo/assets/274700/782195f7-264c-46d6-8d82-277aef981466)

Turns out the cause of this is the plugin we're using to format our HTML, which doesn't know how to handle Hugo templates properly. (It's taking our formatted code and mangling it.) The linked PR removes that plugin.
