### ISSUE TITLE
Docs migration-to-pulumi-from-terraform page Inadequate 

### ISSUE THREAD

**Issue by Yuhta28** [pulumi/pulumi-hugo#3265]
File: [themes/default/content/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform.md](https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform/)

On the [Migrating from Terraform to Pulumi](https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform/#importing-resources) pages, the method for importing an existing resource as described, but the import did not work.  
In the document, [`import.ts`](https://github.com/pulumi/tf2pulumi/blob/master/misc/import/import.ts) file in the already archived tf2pulumi repository is copied to the execution directory to synchronize `.tfstate` file information with Pulumi, but when `pulumi up` command is executed, the following error was displayed.  
```
pulumi up

     Type                 Name                   Plan       Info
 +   pulumi:pulumi:Stack  temp-pulumi-import-s3  create     1 error
 fail
Diagnostics:
  pulumi:pulumi:Stack (temp-pulumi-import-s3):
    error: Running program 'C:\Users\~~~~\' failed with an unhandled exception:
    Error: Only version '3' tfstate files currently supported: 4
        at Object.<anonymous> (C:\Users\~~~~\import.ts:81:35)
        at Module._compile (node:internal/modules/cjs/loader:1254:14)
        at Module.m._compile (C:\Users\~~~~\node_modules\ts-node\src\index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
        at Object.require.extensions.<computed> [as .ts] (C:\Users\~~~~\node_modules\ts-node\src\index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1117:32)
        at Function.Module._load (node:internal/modules/cjs/loader:958:12)
        at Module.require (node:internal/modules/cjs/loader:1141:19)
        at require (node:internal/modules/cjs/helpers:110:18)
        at Object.<anonymous> (C:\Users\~~~~\index.ts:1:1)
```

I think that the import.ts file is archived, so version 4 tfstate files cannot be supported.  How can I solve this problem?

**Comment by interurban** [comment]
Hello @Yuhta28 thanks for submitting this issue as we look into it, if you want more real-time help or if your feeling blocked we have a vibrant community on Slack and our community engineers can help get you unstuck. https://slack.pulumi.com/

**Comment by lukehoban** [comment]
This is the same issue that had been tracked in https://github.com/pulumi/tf2pulumi/issues/241. However, we've since moved to a new model for conversion from Terraform as part of https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/.  That new model does not yet have a replacement for the state conversion.  We are tracking adding that in https://github.com/pulumi/pulumi/issues/5953#issuecomment-1688602915 and https://github.com/pulumi/pulumi-converter-terraform/issues/23.

In the meantime, we will want to update the docs here to not point at the archived (and not currently working for v4 state) import scripts.
