### ISSUE TITLE
Update .NET documentation to remove v3.1 and v5 reference, add v7.

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-hugo#3553]
### What happened?

Our .[NET documentation](https://www.pulumi.com/docs/languages-sdks/dotnet/) states "... you will need to install both Pulumi and .NET Core SDK 3.1, .NET 5, or .NET 6 (recommended)."

However, only .NET6 and 7 are actively [maintained and supported](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle) by Microsoft. And with .NET 8 out in a few weeks.

We should update our documentation so users install the right version.

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

Source ref: https://github.com/pulumi/pulumi-hugo/edit/master/themes/default/content/docs/languages-sdks/dotnet/_index.md

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I recently fixed a similar issue for our references to python versions (https://github.com/pulumi/pulumi-hugo/pull/3249), I suggest we take the same approach here. Nothing in our docs should list a specific version number because that requires us to keep coming back to try and keep them up to date. Instead just refer to Microsofts page for what's supported.

**Comment by aureq** [comment]
@Frassle If you could look at this please https://github.com/pulumi/pulumi-hugo/pull/3573
