### ISSUE TITLE
Pulumi ESC Get Started Contains Typo

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-hugo#3656]
### What happened?

Not positive but it seems there is a typo in Pulumi ESC get started docs. Specifically, `.... in which you need to retrieve lines`, I believe lives should be lines?

Importing Environments
There may be scenarios in which the value you need to retrieve **lives** in a different environment file. For example, since your base application endpoint URL will be the same across environments, it would be more efficient to define it once in one place rather than multiple times across multiple environment files.

### Example

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by interurban** [comment]
thx @phillipedwards !

**Comment by interurban** [comment]
@phillipedwards looking more closely it's not a typo, this is correct "There may be scenarios in which the value you need to retrieve lives in a different environment file. "

that said we can make it more clear, here's what I'll adjust it to: 

There may be scenarios where the value you need to retrieve is stored in a different environment file. For example, since your base application endpoint URL will be the same across environments, it would be more efficient to define it once in one place rather than multiple times across multiple environment files.
