### ISSUE TITLE
No info on "kind" specified.

### ISSUE THREAD

**Issue by nichitacebotari0** [pulumi/pulumi-hugo#3892]
File: [themes/default/content/registry/packages/azure-native/api-docs/web/webapp/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webapp/)

"kind" is simply described as: "Kind of resource", which does. not say much.

**Comment by toriancrane** [comment]
Thank you for submitting this issue @nichitacebotari0! We will take a look into this.

**Comment by nichitacebotari0** [comment]
This is also the case with AppServicePlan by the way, should I open a new issue for that?

**Comment by cnunciato** [comment]
This is good feedback and I agree this could be clearer, but because we generate both the Azure Native provider and its documentation from the Microsoft Azure API specs, we aren't able to fix this issue directly. So unfortunately we'll need to close.  

I believe this is where this definition originates from, however, so you may be able to file an issue here to get it addressed: https://github.com/Azure/azure-rest-api-specs/blob/49486606544ea88451ec53a96994a5ddca42d234/specification/web/resource-manager/Microsoft.Web/stable/2016-03-01/CommonDefinitions.json#L1313
