### ISSUE TITLE
What Python requirements versions should I use for kubernetes?

### ISSUE THREAD

**Issue by tuttle** [pulumi/pulumi-hugo#578]
I tested Pulumi half a year ago successfully. Now I wanted to continue and the command notifies me:

> warning: A new version of Pulumi is available. To upgrade from version '2.23.2' to '3.12.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

Ok, so I visited, navigated to the migration page https://www.pulumi.com/docs/get-started/install/migrating-3.0/. There is presented an excerpt to put to my `requirements.txt`:

```
pulumi>=3.0.0,<4.0.0
pulumi-aws>=4.0.0,<5.0.0
```

But this is **not useful for me**, as I need the version range for `python-kubernetes`. But was unable to find it anywhere. I ended up executing:

```$ ./bin/pip install -U pulumi pulumi-kubernetes```

which installed these without error:

```
$ ./bin/pip freeze -l | grep pulumi
pulumi==3.12.0
pulumi-kubernetes==3.7.1
```

Ok, but I think the version-ranged requirements would be wiser, right? How to achieve that? Thank you.

File: [themes/default/content/docs/get-started/install/migrating-3.0.md](https://www.pulumi.com/docs/get-started/install/migrating-3.0/)

**Comment by leezen** [comment]
I'm a bit confused what you're looking for exactly? The version range from the migration page example is simply showing how you'd stay on a particular major version of that provider. You could similarly specify `>=3.0.0,<4.0.0` to remain on `3.x` of `pulumi-kubernetes` if that's what you want?

**Comment by tuttle** [comment]
Thank you for your response. I'd keep the version range between `pulumi` and `pulumi-kubernetes` in my requirements with only a slight hesitation, if only the the range major versions between `pulumi` and `pulumi-aws` were the same on the example page. But they are not - as I quote here. Hence the reader can infer the development cycles are not synchronized for providers.

**Comment by leezen** [comment]
That's correct that you should not assume that the providers and core Pulumi SDK will version simultaneously. You should treat the core SDK and provider versions independently. Provider versions may undergo major revisions for reasons unrelated to the SDK.

**Comment by tuttle** [comment]
Thank you, Lee. Nevertheless, I'm sorry (and double if my first comment seemed a bit impolite, it was not meant to), this leaves me confused.
You're saying that it is correct to treat version ranges between core and providers independent, so I still miss the information about the correct version range for pulumi-kubernetes for given version range for the core.
For pulumi-aws it is clear from the migration page, the major version is off by one. Where can I find similar reference for pulumi-kubernetes? Thank you.

**Comment by leezen** [comment]
> so I still miss the information about the correct version range for pulumi-kubernetes for given version range for the core.

I think you're expecting that for any given version `pulumi/pulumi` there is some version range for the related provider. The relationship is the reverse. Every provider SDK expects some minimum version of the core SDK and this is encoded in the package as appropriate for the language (e.g. https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/setup.py#L60).

The latest version of any provider is available from the provider's GitHub page (e.g. https://github.com/pulumi/pulumi-kubernetes) along with the version information available in the relevant package manager (e.g. https://pypi.org/project/pulumi-kubernetes/)

Since we're taking advantage of regular programming languages, it is then up to the mechanics of that language ecosystem to appropriately resolve the dependencies such that you have a working set of dependencies. For example, in Python, you might be relying on `conda` or `pip` to setup the correct dependency resolutions while in Node, you'd rely on `npm` or `yarn` to ensure that a compatible set of dependencies are installed.

I'm not sure if this exactly answers your question, but hopefully clarifies what you're trying to understand.

**Comment by tuttle** [comment]
Thank you for taking the time to explain. It's more clear for me now.

The Pulumi team is doing a huge and amazing job overall and I'm not very experienced in this area, so I might certainly still be missing something... but (knowing now that the provider evolution is the driving force for `pulumi/pulumi` upgrade) I think the way the chapter https://www.pulumi.com/docs/get-started/install/migrating-3.0/#update-to-the-new-sdk-version puts things might just create wrong impression.

The chapter IMO says that it is important to pinpoint the `pulumi` package version to be at least 3, whereas it is in fact needed for the user willing to upgrade to find the appropriate **provider version** supporting core version 3.

I feel pinning the version interval of `pulumi` requirement on the page, being provider-dependent from the left (`>=3`) and slightly useless from the right (`<4`), might be even redudant at all.

What I'd find most helpful on the migration page would be some simple instruction **"Modify your requirements.txt in a way that every Pulumi provider (like `pulumi-aws` or `pulumi-kubernetes`) require `pulumi` package version 3."**

Deluxe way would be to list all providers with their respective minimal versions depending on core version 3. :-)

**Comment by leezen** [comment]
@tuttle Sorry if my previous explanation wasn't very good. One thing I should've noted is that whenever we release a new major version of the Pulumi SDK/CLI, we will typically release corresponding major versions of providers that rely on that new `pulumi` SDK. So, in the case of pulumi 3.0, when we released that SDK, we also released a new version of `pulumi-aws` that depended on pulumi 3.0.

The migration page you're referencing is a page designed to help users understand how to migrate from the pulumi v2 to v3 as the SDK itself brings in new features/functionality. Doing that will also require using providers that support that SDK version.

Separate from that, during the regular course of use of Pulumi, you may want to use one provider or another. When using a provider, you should always use the latest version of that provider, which has an underlying dependency on some version of the Pulumi SDK. That provider might also bump in major version due to functionality changes in the provider itself separate from any change in the Pulumi SDK.

Hopefully this clarifies things a little bit better.

**Comment by tuttle** [comment]
Thank you.
