### ISSUE TITLE
add data tracking ids to cloud providers and tutorials links in the docs left nav

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#826]
## overview
we need access to data to know if folks are using the cloud providers and tutorials links in the docs left nav to inform if we want to remove them as part of https://github.com/pulumi/pulumi-hugo/issues/783 and https://github.com/pulumi/pulumi-hugo/issues/784

so.. we need to add IDs to both the cloud providers and tutorials left nav items in the docs

**Comment by susanev** [comment]
i attempted to figure this out on my own, but couldn't really figure out how to make it happen
i did learn that they both get added in the registry repo
https://raw.githubusercontent.com/pulumi/registry/master/themes/default/content/registry/_index.md

**Comment by susanev** [comment]
@cnunciato if you happen to have any hints you can give me about how to do this id appreciate it

**Comment by cnunciato** [comment]
@susanev Yeah, this all happens in https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/layouts/partials/docs/toc.html. There isn't an easy way to target _just those_ links, but you can add IDs to pretty much all of them on these two lines (though of course you'd have to map their names or paths or some other property to valid IDs):

https://github.com/pulumi/pulumi-hugo/blob/598bab4064c7a5d02e6a6c9ef22b02d57c01974f/themes/default/layouts/partials/docs/toc.html#L56

https://github.com/pulumi/pulumi-hugo/blob/598bab4064c7a5d02e6a6c9ef22b02d57c01974f/themes/default/layouts/partials/docs/toc.html#L66

Still, I know we currently use `data-track` properties (rather than `id`s) for the links we want to monitor. @zchase Is that still the case? If we add unique `data-track`s to these links, will we get the counts we want for these?

**Comment by susanev** [comment]
i should have linked to this [internal slack convo ](https://pulumi.slack.com/archives/CECFE3YJZ/p1636041608009700)in the description

**Comment by zchase** [comment]
@susanev @cnunciato Yeah if you add the `data-track` attribute a link it should be marked appropriately in GA Events.

https://github.com/pulumi/theme/blob/master/src/ts/tracking.ts#L27

**Comment by susanev** [comment]
okay now about the uniqueness, i found that folks often use `{{ now.UnixNano }}` but that wont work for us i don't think because we don't want it to change when the docs rebuild. i also found folks hashing Inner, but you cant use Inner in a partial. any of yall have ideas on how to get unique values?

cc/ @cnunciato @zchase

**Comment by cnunciato** [comment]
@susanev Correct -- that, and if you look around at the `data-track` names we're using now, they're also human-readable (so we can go back and find them later). 

We can probably just `urlize` the link labels somehow with a prefix, like what @zchase has here:

https://github.com/pulumi/pulumi-hugo/blob/598bab4064c7a5d02e6a6c9ef22b02d57c01974f/themes/default/layouts/blog/list.html#L13

I see we're using `toc-` as a prefix already in `toc.html`:

https://github.com/pulumi/pulumi-hugo/blob/598bab4064c7a5d02e6a6c9ef22b02d57c01974f/themes/default/layouts/partials/docs/toc.html#L4

... so it might make sense to do with the same convention for this stuff.

**Comment by susanev** [comment]
okay yes, i have that, i should have just shared what i have so far. but i was worried about it possibly not being unique if i don't also append a unique value. but maybe i was being silly.

**Comment by cnunciato** [comment]
> i was worried about it possibly not being unique

Yeah, I just went back and added a little note, as I didn't make that super clear. That should be fine, especially if it's prefixed with `toc-`.

**Comment by susanev** [comment]
also this days to use data-tracking-id, has that since changed to be data-track?
https://github.com/pulumi/theme/blob/master/src/ts/tracking.ts#L5

**Comment by cnunciato** [comment]
Yep yep, that comment's just wrong. It's `data-track`.

**Comment by susanev** [comment]
k will fix
